export let phrases =
    [
        { phrase: "Ask not what your country can do for you, ask what you can do for your country.", author: "John F. Kennedy" },
        { phrase: "I have a dream", author: "Martin Luther King Jr." },
        { phrase: "The only thing we have to fear is fear itself", author: "Franklin D. Roosevelt" },
        { phrase: "Imagine all the people living life in peace", author: "John Lennon" },
        { phrase: "To be or not to be, that is the question", author: "William Shakespeare" },
        { phrase: "The best way to predict the future is to create it", author: "Abraham Lincoln" },
        { phrase: "Emancipate yourselves from mental slavery, none but ourselves can free our minds", author: "Bob Marley" },
        { phrase: "If you want to live a happy life, tie it to a goal, not to people or things", author: "Albert Einstein" },
        { phrase: "The only thing necessary for the triumph of evil is for good men to do nothing", author: "Edmund Burke" },
        { phrase: "Where there is love, there is life", author: "Mahatma Gandhi" },
        { phrase: "Success is not final, failure is not fatal: it is the courage to continue that counts", author: "Winston Churchill" },
        { phrase: "I think, therefore I am", author: "René Descartes" },
        { phrase: "It does not matter how slowly you go as long as you do not stop", author: "Confucius" },
        { phrase: "I am who I am, your approval is not needed", author: "Unknown" },
        { phrase: "Life is not a problem to be solved, but a reality to be experienced", author: "Søren Kierkegaard" },
        { phrase: "If you can dream it, you can do it", author: "Walt Disney" },
        { phrase: "You can't always get what you want, but if you try sometimes, you might find you get what you need", author: "Mick Jagger" },
        { phrase: "The only limit to our realization of tomorrow will be our doubts of today", author: "Franklin D. Roosevelt" },
        { phrase: "It's not the years in your life that count. It's the life in your years", author: "Abraham Lincoln" },
        { phrase: "You miss 100% of the shots you don't take", author: "Wayne Gretzky" },
        { phrase: "Knowledge speaks, but wisdom listens", author: "Jimi Hendrix" },
        { phrase: "In three words I can sum up everything I've learned about life: it goes on", author: "Robert Frost" },
        { phrase: "In the end, we will remember not the words of our enemies, but the silence of our friends", author: "Martin Luther King Jr." },
        { phrase: "Believe you can and you're halfway there", author: "Theodore Roosevelt" },
        { phrase: "Don't watch the clock; do what it does. Keep going", author: "Sam Levenson" },
        { phrase: "Great minds discuss ideas; average minds discuss events; small minds discuss people", author: "Eleanor Roosevelt" },
        { phrase: "Life is 10% what happens to us and 90% how we react to it", author: "Charles R. Swindoll" }
    ]